## netlify cms config
## the rest of this is in admin/index.html
backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"

collections:
  - name: "Events"
    label: "Events" # Used in the UI
    # folder: "data/events" # The path to the folder where the documents are stored
    # create: true # Allow users to create new documents in this collection
    # extension: yml # https://www.netlifycms.org/docs/configuration-options/#extension-and-format
    # identifier_field: eventName # https://www.netlifycms.org/docs/collection-types/#folder-collections
    # slug: "{{slug}}" # Filename template, e.g., title.md
    files:
      - label: Event
        name: event
        file: "data/events.yml"
        widget: list
        fields:
          - {label: "Event Name", name: "eventName", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "Country", name: "country", widget: "string", hint: "Something someone might search, e.g. USA, UK, Sweden, Singapore, Remote"}
          - {label: "City", name: "city", widget: "string", hint: "Something someone might search, e.g. NYC, London, Stockholm, Singapore, Remote"}
          - label: "Type"
            name: "type"
            widget: "select"
            options: 
              - {label: "Recurring Meetup", value: "meetup"}
              - {label: "One-off Event", value: "oneoff"}
              - {label: "Workshop", value: "workshop"}
              - {label: "Conference", value: "conference"}
              - {label: "Misc Event", value: "misc"}
          - {label: "Twitter", name: "twitter", widget: "string", required: false}
          - {label: "Specific Date (if applicable)", name: "date", widget: "datetime", required: false}
          - {label: "Organizer Contact", name: "organizer", widget: "text", hint: "your name, email, twitter, any way for people to get in touch", required: false }
          - {label: "Optional Cover Image", required: false, name: "thumbnail", widget: "image" }
          - {label: "Short Description", name: "desc", widget: "string", required: false}
          - {label: "Full Description", name: "description", widget: "markdown", required: false}